import {
  toggleOption, lineTypeOption,
  colourOption, numberOption,
  fontOption, fontSizeOption, textOption,
  lineLabelPositionOption
} from "./common";

const linesSettings = {
  description: "Linjer",
  displayName: "Linjer",
  settingsGroups: {
    "Hovedlinje": {
      show_main: toggleOption("Vis datalinje", true),
      width_main: numberOption("Linjetykkelse", 1, { min: 0, max: 100 }),
      type_main: lineTypeOption("Linjetype", "10 0"),
      colour_main: colourOption("Linjefarve", "common_cause"),
      opacity_main: numberOption("Gennemsigtighed", 1, { min: 0, max: 1 }),
      opacity_unselected_main: numberOption("Gennemsigtighed (andre valgt)", 0.2, { min: 0, max: 1 }),
      join_rebaselines_main: toggleOption("Forbind linjer over faseskift", false),
      plot_label_show_main: toggleOption("Vis værdi på diagram", false),
      plot_label_show_all_main: toggleOption("Vis værdi ved alle faser", false),
      plot_label_show_n_main: numberOption("Vis værdi ved seneste N faser", 1, { min: 1 }),
      plot_label_position_main: lineLabelPositionOption(),
      plot_label_vpad_main: numberOption("Lodret afstand", 0),
      plot_label_hpad_main: numberOption("Vandret afstand", 10),
      plot_label_font_main: fontOption("Skrifttype"),
      plot_label_size_main: fontSizeOption("Skriftstørrelse"),
      plot_label_colour_main: colourOption("Skriftfarve", "standard"),
      plot_label_prefix_main: textOption("Tekstpræfiks", "")
    },
    "Centerlinje": {
      show_target: toggleOption("Vis centerlinje", true),
      width_target: numberOption("Linjetykkelse", 1.5, { min: 0, max: 100 }),
      type_target: lineTypeOption("Linjetype", "10 0"),
      colour_target: colourOption("Linjefarve", "standard"),
      opacity_target: numberOption("Gennemsigtighed", 1, { min: 0, max: 1 }),
      opacity_unselected_target: numberOption("Gennemsigtighed (andre valgt)", 0.2, { min: 0, max: 1 }),
      join_rebaselines_target: toggleOption("Forbind linjer over faseskift", false),
      ttip_show_target: toggleOption("Vis værdi i tooltip", true),
      ttip_label_target: textOption("Tooltip-etiket", "Centerlinje"),
      plot_label_show_target: toggleOption("Vis værdi på diagram", false),
      plot_label_show_all_target: toggleOption("Vis værdi ved alle faser", false),
      plot_label_show_n_target: numberOption("Vis værdi ved seneste N faser", 1, { min: 1 }),
      plot_label_position_target: lineLabelPositionOption(),
      plot_label_vpad_target: numberOption("Lodret afstand", 0),
      plot_label_hpad_target: numberOption("Vandret afstand", 10),
      plot_label_font_target: fontOption("Skrifttype"),
      plot_label_size_target: fontSizeOption("Skriftstørrelse"),
      plot_label_colour_target: colourOption("Skriftfarve", "standard"),
      plot_label_prefix_target: textOption("Tekstpræfiks", "")
    },
    "Mållinje": {
      show_alt_target: toggleOption("Vis mållinje", false),
      alt_target: numberOption("Målværdi:", undefined),
      multiplier_alt_target: toggleOption("Anvend multiplikator på mållinje", false),
      width_alt_target: numberOption("Linjetykkelse", 1.5, { min: 0, max: 100 }),
      type_alt_target: lineTypeOption("Linjetype", "10 0"),
      colour_alt_target: colourOption("Linjefarve", "standard"),
      opacity_alt_target: numberOption("Gennemsigtighed", 1, { min: 0, max: 1 }),
      opacity_unselected_alt_target: numberOption("Gennemsigtighed (andre valgt)", 0.2, { min: 0, max: 1 }),
      join_rebaselines_alt_target: toggleOption("Forbind linjer over faseskift", false),
      ttip_show_alt_target: toggleOption("Vis værdi i tooltip", true),
      ttip_label_alt_target: textOption("Tooltip-etiket", "Mållinje"),
      plot_label_show_alt_target: toggleOption("Vis værdi på diagram", false),
      plot_label_show_all_alt_target: toggleOption("Vis værdi ved alle faser", false),
      plot_label_show_n_alt_target: numberOption("Vis værdi ved seneste N faser", 1, { min: 1 }),
      plot_label_position_alt_target: lineLabelPositionOption(),
      plot_label_vpad_alt_target: numberOption("Lodret afstand", 0),
      plot_label_hpad_alt_target: numberOption("Vandret afstand", 10),
      plot_label_font_alt_target: fontOption("Skrifttype"),
      plot_label_size_alt_target: fontSizeOption("Skriftstørrelse"),
      plot_label_colour_alt_target: colourOption("Skriftfarve", "standard"),
      plot_label_prefix_alt_target: textOption("Tekstpræfiks", "")
    },
    "95%-kontrolgrænser": {
      show_95: toggleOption("Vis 95%-kontrolgrænser", false),
      width_95: numberOption("Linjetykkelse", 2, { min: 0, max: 100 }),
      type_95: lineTypeOption("Linjetype", "2 5"),
      colour_95: colourOption("Linjefarve", "limits"),
      opacity_95: numberOption("Gennemsigtighed", 1, { min: 0, max: 1 }),
      opacity_unselected_95: numberOption("Gennemsigtighed (andre valgt)", 0.2, { min: 0, max: 1 }),
      join_rebaselines_95: toggleOption("Forbind linjer over faseskift", false),
      ttip_show_95: toggleOption("Vis værdi i tooltip", true),
      ttip_label_95: textOption("Tooltip-etiket", "95%-grænse"),
      ttip_label_95_prefix_lower: textOption("Tooltip-præfiks (nedre)", "Nedre "),
      ttip_label_95_prefix_upper: textOption("Tooltip-præfiks (øvre)", "Øvre "),
      plot_label_show_95: toggleOption("Vis værdi på diagram", false),
      plot_label_show_all_95: toggleOption("Vis værdi ved alle faser", false),
      plot_label_show_n_95: numberOption("Vis værdi ved seneste N faser", 1, { min: 1 }),
      plot_label_position_95: lineLabelPositionOption(),
      plot_label_vpad_95: numberOption("Lodret afstand", 0),
      plot_label_hpad_95: numberOption("Vandret afstand", 10),
      plot_label_font_95: fontOption("Skrifttype"),
      plot_label_size_95: fontSizeOption("Skriftstørrelse"),
      plot_label_colour_95: colourOption("Skriftfarve", "standard"),
      plot_label_prefix_95: textOption("Tekstpræfiks", "")
    },
    "99%-kontrolgrænser": {
      show_99: toggleOption("Vis 99%-kontrolgrænser", true),
      width_99: numberOption("Linjetykkelse", 2, { min: 0, max: 100 }),
      type_99: lineTypeOption("Linjetype", "10 10"),
      colour_99: colourOption("Linjefarve", "limits"),
      opacity_99: numberOption("Gennemsigtighed", 1, { min: 0, max: 1 }),
      opacity_unselected_99: numberOption("Gennemsigtighed (andre valgt)", 0.2, { min: 0, max: 1 }),
      join_rebaselines_99: toggleOption("Forbind linjer over faseskift", false),
      ttip_show_99: toggleOption("Vis værdi i tooltip", true),
      ttip_label_99: textOption("Tooltip-etiket", "99%-grænse"),
      ttip_label_99_prefix_lower: textOption("Tooltip-præfiks (nedre)", "Nedre "),
      ttip_label_99_prefix_upper: textOption("Tooltip-præfiks (øvre)", "Øvre "),
      plot_label_show_99: toggleOption("Vis værdi på diagram", false),
      plot_label_show_all_99: toggleOption("Vis værdi ved alle faser", false),
      plot_label_show_n_99: numberOption("Vis værdi ved seneste N faser", 1, { min: 1 }),
      plot_label_position_99: lineLabelPositionOption(),
      plot_label_vpad_99: numberOption("Lodret afstand", 0),
      plot_label_hpad_99: numberOption("Vandret afstand", 10),
      plot_label_font_99: fontOption("Skrifttype"),
      plot_label_size_99: fontSizeOption("Skriftstørrelse"),
      plot_label_colour_99: colourOption("Skriftfarve", "standard"),
      plot_label_prefix_99: textOption("Tekstpræfiks", "")
    },

  }
};

export default linesSettings;
