"use strict";

import type powerbi from "powerbi-visuals-api";
type VisualUpdateOptions = powerbi.extensibility.visual.VisualUpdateOptions;
type ISelectionId = powerbi.visuals.ISelectionId;
import * as d3 from "./D3 Plotting Functions/D3 Modules";
import drawXAxis from "./D3 Plotting Functions/drawXAxis";
import drawYAxis from "./D3 Plotting Functions/drawYAxis";
import drawTooltipLine from "./D3 Plotting Functions/drawTooltipLine";
import drawLimitBand from "./D3 Plotting Functions/drawLimitBand";
import drawLines from "./D3 Plotting Functions/drawLines";
import drawDots from "./D3 Plotting Functions/drawDots";
import addContextMenu from "./D3 Plotting Functions/addContextMenu";
import drawErrors from "./D3 Plotting Functions/drawErrors";
import initialiseSVG from "./D3 Plotting Functions/initialiseSVG";
import drawSummaryTable from "./D3 Plotting Functions/drawSummaryTable";
import drawValueLabels from "./D3 Plotting Functions/drawValueLabels";
import drawLineLabels from "./D3 Plotting Functions/drawLineLabels";
import drawSignalPanel from "./D3 Plotting Functions/drawSignalPanel";
import drawWarning from "./D3 Plotting Functions/drawWarning";
import plotPropertiesClass from "./Classes/plotPropertiesClass";
import viewModelClass, { type plotData, type viewModelValidationT } from "./Classes/viewModelClass";
import type { lineData, plotDataGrouped } from "./Classes/viewModelClass";
import getAesthetic from "./Functions/getAesthetic";
import identitySelected from "./Functions/identitySelected";

export type svgBaseType = d3.Selection<SVGSVGElement, unknown, null, undefined>;
export type divBaseType = d3.Selection<HTMLDivElement, unknown, null, undefined>;

// Luft mellem en linjeetiket og signalpanelets venstre kant.
const LABEL_PANEL_GAP: number = 8;

export class Visual implements powerbi.extensibility.IVisual {
  host: powerbi.extensibility.visual.IVisualHost;
  tableDiv: divBaseType;
  svg: svgBaseType;
  viewModel: viewModelClass;
  plotProperties: plotPropertiesClass;
  selectionManager: powerbi.extensibility.ISelectionManager;

  constructor(options?: powerbi.extensibility.visual.VisualConstructorOptions) {
    // The plugin scaffold generated by powerbi-visuals-tools types its
    // `create` callback argument as optional, so the constructor has to
    // accept that shape. Power BI always supplies it at runtime.
    if (!options) {
      throw new Error("Visual constructor called without VisualConstructorOptions");
    }

    this.tableDiv = d3.select(options.element).append("div")
                                              .style("overflow", "auto");

    this.svg = d3.select(options.element).append("svg");
    this.host = options.host;
    this.viewModel = new viewModelClass();
    this.plotProperties = new plotPropertiesClass();

    this.selectionManager = this.host.createSelectionManager();
    this.selectionManager.registerOnSelectCallback(() => this.updateHighlighting());

    this.svg.call(initialiseSVG);
    const table = this.tableDiv.append("table")
                                .classed("table-group", true)
                                .style("border-collapse", "collapse")
                                .style("width", "100%")
                                .style("height", "100%");

    table.append("thead").append("tr").classed("table-header", true);
    table.append('tbody').classed("table-body", true);
  }

  public update(options: VisualUpdateOptions): void {
    try {
      this.host.eventService.renderingStarted(options);
      // Remove printed error if refreshing after a previous error run
      this.svg.select(".errormessage").remove();

      // This step handles the updating of both the input data and settings
      // If there are any errors or failures, the update exits early sets the
      // update status to false
      const update_status: viewModelValidationT = this.viewModel.update(options, this.host);
      if (!update_status.status) {
        this.plotProperties.displayPlot = false;
        this.resizeCanvas(options.viewport.width, options.viewport.height);
        if (this.viewModel?.inputSettings?.settings?.[0]?.canvas?.show_errors ?? true) {
          this.svg.call(drawErrors, options, this.viewModel.colourPalette, update_status?.error ?? "", update_status?.type ?? "");
        } else {
          this.svg.call(initialiseSVG, true);
        }

        this.host.eventService.renderingFailed(options);
        return;
      }

      this.plotProperties.update(options, this.viewModel);

      if (update_status.warning) {
        this.host.displayWarningIcon("Invalid inputs or settings ignored.\n",
                                      update_status.warning);
      }

      if (this.viewModel.showGrouped || this.viewModel.inputSettings.settings[0].summary_table.show_table) {
        this.resizeCanvas(0, 0);
        this.tableDiv.call(drawSummaryTable, this)
                     .call(addContextMenu, this);
      } else {
        this.resizeCanvas(options.viewport.width, options.viewport.height);
        this.drawVisual();
        this.adjustPaddingForPanel();
        this.adjustPaddingForOverflow();
      }

      this.updateHighlighting();
      this.host.eventService.renderingFinished(options);
    } catch (caught_error) {
      this.resizeCanvas(options.viewport.width, options.viewport.height);
      this.svg.call(drawErrors, options, this.viewModel.colourPalette, (caught_error as Error).message, "internal");
      console.error(caught_error);
      this.host.eventService.renderingFailed(options);
    }
  }

  drawVisual(): void {
    this.svg.call(drawXAxis, this)
            .call(drawYAxis, this)
            .call(drawTooltipLine, this)
            .call(drawLimitBand, this)
            .call(drawLines, this)
            .call(drawLineLabels, this)
            .call(drawDots, this)
            .call(addContextMenu, this)
            .call(drawValueLabels, this)
            .call(drawSignalPanel, this)
            .call(drawWarning, this);
  }

  /**
   * Giver linjeetiketterne plads, hvor signalpanelet står.
   *
   * Indstillingen "Margen til højre" er et rimeligt gæt på, hvor bred en
   * etiket bliver, men bredden afhænger af tallet: "50,90" fylder en tredjedel
   * af "1.234.567,89". Her måles den faktiske etiket, og margenen udvides med
   * præcis det, der mangler — indstillingen bliver dermed et minimum frem for
   * et tal, brugeren selv skal ramme.
   *
   * Kun panelets kant: lærredets egen kant håndteres af
   * adjustPaddingForOverflow, som kører umiddelbart efter.
   */
  adjustPaddingForPanel(): void {
    // Uden layout (headless eksport) er der intet at måle.
    if (this.viewModel.headless || !this.plotProperties.showSignalPanel) {
      return;
    }
    const panelLeft: number = this.viewModel.svgWidth
                              - this.viewModel.inputSettings.settings[0].signal_panel.panel_width;
    let overlap: number = 0;
    this.svg.selectAll<SVGGraphicsElement, unknown>(".linesgroup text").each(function() {
      const box: DOMRect = this.getBBox();
      // En tom etiket har ingen boks at måle.
      if (box.width > 0) {
        overlap = Math.max(overlap, box.x + box.width + LABEL_PANEL_GAP - panelLeft);
      }
    });

    if (overlap > 0) {
      this.plotProperties.xAxis.end_padding += overlap;
      this.plotProperties.initialiseScale(this.viewModel.svgWidth, this.viewModel.svgHeight);
      this.drawVisual();
    }
  }

  adjustPaddingForOverflow(): void {
    // Headless mode does not render to screen so do not attempt to adjust for overflow
    if (this.viewModel.headless) {
      return;
    }
    const svgWidth: number = this.viewModel.svgWidth;
    const svgHeight: number = this.viewModel.svgHeight;
    const svgBBox: DOMRect = (this.svg.node() as SVGSVGElement).getBBox();
    const overflowLeft: number = Math.abs(Math.min(0, svgBBox.x));
    const overflowRight: number = Math.max(0, svgBBox.width + svgBBox.x - svgWidth);
    const overflowTop: number = Math.abs(Math.min(0, svgBBox.y));
    const overflowBottom: number = Math.max(0, svgBBox.height + svgBBox.y - svgHeight);
    if (overflowLeft > 0) {
      this.plotProperties.xAxis.start_padding += overflowLeft + this.plotProperties.xAxis.start_padding;
    }
    if (overflowRight > 0) {
      this.plotProperties.xAxis.end_padding += overflowRight + this.plotProperties.xAxis.end_padding;
    }
    if (overflowTop > 0) {
      this.plotProperties.yAxis.end_padding += overflowTop + this.plotProperties.yAxis.end_padding;
    }
    if (overflowBottom > 0) {
      this.plotProperties.yAxis.start_padding += overflowBottom + this.plotProperties.yAxis.start_padding;
    }
    if (overflowLeft > 0 || overflowRight > 0 || overflowTop > 0 || overflowBottom > 0) {
      this.plotProperties.initialiseScale(svgWidth, svgHeight);
      this.drawVisual();
    }
  }

  resizeCanvas(width: number, height: number): void {
    this.svg.attr("width", width).attr("height", height);
    if (width === 0 && height === 0) {
      this.tableDiv.style("width", "100%").style("height", "100%");
    } else {
      this.tableDiv.style("width", "0%").style("height", "0%");
    }
  }

  updateHighlighting(): void {
    const anyHighlights: boolean = this.viewModel.inputData.length > 0
      && this.viewModel.inputData.some(d => d.anyHighlights);
    const allSelectionIDs: ISelectionId[] = this.selectionManager.getSelectionIds() as ISelectionId[];

    const dotsSelection: d3.Selection<d3.BaseType | SVGPathElement, plotData, d3.BaseType, unknown> = this.svg.selectAll(".dotsgroup").selectChildren();
    const linesSelection: d3.Selection<d3.BaseType | SVGGElement, [string, lineData[]], d3.BaseType, unknown> = this.svg.selectAll(".linesgroup").selectChildren();
    const tableSelection: d3.Selection<d3.BaseType | HTMLTableRowElement, plotDataGrouped, d3.BaseType, unknown> = this.tableDiv.selectAll(".table-body").selectChildren();

    // Set all elements to their default opacity before applying highlights
    linesSelection.style("stroke-opacity", (d: [string, lineData[]]) => {
      return getAesthetic(d[0], "lines", "opacity", this.viewModel.inputSettings.settings[0])
    });
    dotsSelection.style("fill-opacity", (d: plotData) => d.aesthetics.opacity);
    dotsSelection.style("stroke-opacity", (d: plotData) => d.aesthetics.opacity);
    tableSelection.style("opacity", (d: plotDataGrouped) => d.aesthetics.table_opacity);

    if (anyHighlights || (allSelectionIDs.length > 0)) {
      linesSelection.style("stroke-opacity", (d: [string, lineData[]]) => {
        return getAesthetic(d[0], "lines", "opacity_unselected", this.viewModel.inputSettings.settings[0])
      });
      dotsSelection.nodes().forEach(currentDotNode => {
        const dot: plotData = d3.select(currentDotNode).datum() as plotData;
        const currentPointSelected: boolean = identitySelected(dot.identity, this.selectionManager);
        const currentPointHighlighted: boolean = dot.highlighted;
        const newDotOpacity: number = (currentPointSelected || currentPointHighlighted) ? dot.aesthetics.opacity_selected  : dot.aesthetics.opacity_unselected;
        d3.select(currentDotNode).style("fill-opacity", newDotOpacity);
        d3.select(currentDotNode).style("stroke-opacity", newDotOpacity);
      })

      tableSelection.nodes().forEach(currentTableNode => {
        const dot: plotDataGrouped = d3.select(currentTableNode).datum() as plotDataGrouped;
        const currentPointSelected: boolean = identitySelected(dot.identity, this.selectionManager);
        const currentPointHighlighted: boolean = dot.highlighted;
        const newTableOpacity: number = (currentPointSelected || currentPointHighlighted) ? dot.aesthetics["table_opacity_selected"] : dot.aesthetics["table_opacity_unselected"];
        d3.select(currentTableNode).style("opacity", newTableOpacity);
      })
    }
  }

  public getFormattingModel(): powerbi.visuals.FormattingModel {
    return this.viewModel.inputSettings.getFormattingModel();
  }
}
